### ISSUE TITLE
Suggestion to Update Installation Instructions and Dependencies

### ISSUE THREAD

**Issue by SebasAL14** [pycolibri/pycolibri#156]
While attempting to install the repository in a Conda environment on Windows, I encountered a couple of points that might benefit from clarification and updating:

1. After following step 2 ("Create a virtual environment with Conda:"), it would be helpful to include an additional step to navigate to the pycolibri directory using: `cd pycolibri` .
2. I created the environment using Conda with Python version 3.10.14. Upon installing the requirements and running the test code, I noticed that the specified package versions are no longer compatible with my environment. To resolve this, I referred to the latest PyTorch documentation and successfully installed the necessary packages using the following command: `conda install pytorch torchvision torchaudio cpuonly -c pytorch` .

I believe these updates will streamline the installation process for future users. Please let me know if further clarification is needed.

Thank you for your attention to this matter!

**Comment by David-Morales-Norato** [comment]
Additionally, requeriments.py contains redundant information with setup.py. 

setup.py could read the requirements list and only have this information in one file
